version: "3.4"
services:
  genetic_flask:
    container_name: genetic
    image: aimvector/python:1.0.0
    build:
      context: ./app
      target: debug
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app/main.py
    volumes:
    - ./app/:/work
    ports:
      - 5000:5000
      - 5678:5678