services:
  genetic_flask:
    container_name: genetic
    build:
      context: ./
      target: prod
    environment:
      FLASK_DEBUG: 1
    volumes:
    - ./:/work
    ports:
      - 5000:5000
      - 5678:5678